### ISSUE TITLE
regular expression: {s<=2}

### ISSUE THREAD

**Issue by WilsonYangLiu** [rohansachdeva/assembly_repeats#1]
https://github.com/rohansachdeva/assembly_repeats/blob/ff8c642f2cf927e7306098b6f32fd660de260807/assembly_repeats.py#L54

I can not understand, can you tell me what this regex mean？Thank you

**Comment by rohansachdeva** [comment]
Hi - The point of this function that the regex is part is to look for sequences that are repeating concatenations of a single sequence. 
 
The regex: `rx = f'({fraction_seq})' + regex_subs ` is looking for `fraction_seq` in the sequence. 

`fraction_seq` is defined as 20% of the whole sequence. So we're looking for matches of the first 20% of the sequence in the rest of the sequence allowing for 2 mismatches (defined by `regex_subs`).
